# Generated by Django 4.2.1 on 2023-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=45)),
                ('idade', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios_fbv',
            },
        ),
    ]
